USE [corredora]
GO
/****** Object:  StoredProcedure [dbo].[sp_deudaArrentarioParticular]    Script Date: 25-04-2015 00:48:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author: Abdon Sandoval
-- Create date: 24-04-2015
-- Description: Muestra deuda de un arrendatario consultado por rut, este entrega el TOTAL y el DETALLE de dicho TOTAL
-- =============================================
CREATE PROCEDURE [dbo].[sp_deudaArrentarioParticular]
@rut AS INT

AS
BEGIN
DECLARE @existe AS INT
SET @existe = (SELECT COUNT(1) FROM ARRENDATARIO WHERE RUTARRENDATARIO=@rut)

IF @existe = 0
SELECT 'RUT NO EXISTE VERIFIQUE'
ELSE
BEGIN
--cuando debe un arrendatario en particular
SELECT SUM(VALORARRIENDO) AS DEUTA_TOTAL
FROM CONTRATO AS CO INNER JOIN CUOTASARRIENDO AS CA ON CO.IDCONTRATO = CA.IDCONTRATO INNER JOIN ESTADOPAGO AS E ON E.IDESTADOPAGO = CA.IDESTADOPAGO
WHERE CO.RUTARRENDATARIO = @rut AND CA.IDESTADOPAGO IN (2,3)

--detalle de dicha deuda
SELECT CO.RUTARRENDATARIO, CO.VALORARRIENDO, CO.DIAPAGO, CO.NUMEROCUOTAS, CO.FECHACONTRATO,  E.DESCRIPCION, CA.FECHAPAGO,  P.DIRECCION
FROM CONTRATO AS CO INNER JOIN CUOTASARRIENDO AS CA ON CO.IDCONTRATO = CA.IDCONTRATO INNER JOIN ESTADOPAGO AS E ON E.IDESTADOPAGO = CA.IDESTADOPAGO JOIN PROPIEDAD AS P ON P.IDPROPIEDAD=CO.IDPROPIEDAD
WHERE CO.RUTARRENDATARIO = @rut AND CA.IDESTADOPAGO IN (2,3)

END

END