CREATE PROCEDURE sp_InfoPropiedad

@idpropiedad AS INT

AS
BEGIN
	SELECT p.DIRECCION, p.COMUNA,p.CUIDAD,p.VALORARRIENDO,d.NOMBRE AS DUEÑO,d.APATERNO AS APELLIDO, p.PIEZAS,p.BANOS,p.ARRENDADO,
	a.NOMBRE AS ARRENDATARIO,a.APATERNO AS APELLIDO ,c.FECHATERMINO AS FECHATERMINO_CONTRATO
	FROM PROPIEDAD AS p join CONTRATO AS c on p.IDPROPIEDAD=c.IDPROPIEDAD join 
	ARRENDATARIO AS a ON a.RUTARRENDATARIO = c.RUTARRENDATARIO join 
	TIPOPROPIEDAD AS t ON t.IDTIPO=p.IDTIPO join 
	DUENO AS d ON d.RUTDUENO = p.RUTDUENO
	WHERE p.IDPROPIEDAD=1
END